                                    #########################################################################                                    
                                    ######################  API ENDPOINTS TESTS   ###########################
                                    #########################################################################


#GET ALL Accounts by table name
GET http://5.196.63.217:3001/api/generateTokenForUser/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQ3OTU2MTQsImV4cCI6MTYyNTMxMTYxNH0.jVgiO2CA-vVXlT3fkGZyFUtRPytSoqm7YU03IduLB8g

{
   
}

###

#Find an item with his id
POST http://localhost:2001/api/account/SignIn
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjU4NjI2MDIsImV4cCI6MTYyNjM3ODYwMn0.jtw845wk21XyGXMKavn7MQS8lEbp87WtKQ_KiYZVzgA

{
    "username":"admin",
    "password":"Gabes2017."

}
###

#Find an item with his id
POST http://localhost:2001/api/account/getAccountByToken
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYyNTkzNDEwNCwiZXhwIjoxNjI2NDUwMTA0fQ.Jxs_ij0d2IaW9H4SvNLmboW3JK6ks0uC5zWnV5GHlcE

{


}
###

#Find an item with his id
POST http://5.196.63.217:3001/api/account/find
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjcxNDgxODEsImV4cCI6MTYyNzY2NDE4MX0.PIGvQzZyJD71LSYtZ0oWjI5bmqRqzAfhj6fUVhapLM0

{
   

}
###

#Create and Save a new item
PUT http://localhost:2001/api/campaign/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjU4NjI2MDIsImV4cCI6MTYyNjM3ODYwMn0.jtw845wk21XyGXMKavn7MQS8lEbp87WtKQ_KiYZVzgA

{
        "campaign_id": 1,
          "call_status" : {"test" : 1}
    
}

###

###

#Search Items by their accountname 
GET  http://localhost:3000/api/account/search/
Content-Type: application/json

{
    "call_status" : "test loger2"
}

###

#Update an item by ID
PUT http://localhost:3000/api/account/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQ3OTU2MTQsImV4cCI6MTYyNTMxMTYxNH0.jVgiO2CA-vVXlT3fkGZyFUtRPytSoqm7YU03IduLB8g

{
     "account_id": 8,
    "account_code": "account_code 4",
    "first_name": "first_name 2",
    "last_name": "last_name 2",
    "company": "company 2"

}

###

#Delete an item by ID
DELETE http://localhost:3000/api/account/delete/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQ3OTU2MTQsImV4cCI6MTYyNTMxMTYxNH0.jVgiO2CA-vVXlT3fkGZyFUtRPytSoqm7YU03IduLB8g


###
