#GET ACL Groups
GET https://92.222.227.222:1443/api/v1/acl_groups
Content-Type: application/json
Authorization: Bearer U0wglx83RzOBnkb755i8MpZtsuEjna1M7D042fihMXwJs4Tj8uhnsGuK9cIi2IY5

###

#Create ACL Group By Id
GET https://occ.oxilog.net:1443/api/v1/acl_groups/2
Content-Type: application/json
Authorization: Bearer U0wglx83RzOBnkb755i8MpZtsuEjna1M7D042fihMXwJs4Tj8uhnsGuK9cIi2IY5


###

#Create ACL Group
POST https://occ.oxilog.net:1443/api/v1/acl_groups
Content-Type: application/json
Authorization: Bearer U0wglx83RzOBnkb755i8MpZtsuEjna1M7D042fihMXwJs4Tj8uhnsGuK9cIi2IY5

{
  "name": "freeswitch-servers",
  "description": "freeswitch-servers"
}

###

#Update ACL Group
PUT https://occ.oxilog.net:1443/api/v1/acl_groups/2
Content-Type: application/json
Authorization: Bearer U0wglx83RzOBnkb755i8MpZtsuEjna1M7D042fihMXwJs4Tj8uhnsGuK9cIi2IY5

{
  "name": "providers",
  "description": "SIP Providers Group"
}

###

#Delete ACL Group
DELETE https://occ.oxilog.net:1443/api/v1/acl_groups/1
Content-Type: application/json
Authorization: Bearer U0wglx83RzOBnkb755i8MpZtsuEjna1M7D042fihMXwJs4Tj8uhnsGuK9cIi2IY5

###



###

#GET ACLs
GET https://occ.oxilog.net:1443/api/v1/acl_groups/2/acls
Content-Type: application/json
Authorization: Bearer U0wglx83RzOBnkb755i8MpZtsuEjna1M7D042fihMXwJs4Tj8uhnsGuK9cIi2IY5

###

#GET ACL By Id
GET https://occ.oxilog.net:1443/api/v1/acl_groups/3/acls/1
Content-Type: application/json
Authorization: Bearer U0wglx83RzOBnkb755i8MpZtsuEjna1M7D042fihMXwJs4Tj8uhnsGuK9cIi2IY5

###

#Create Acl
POST https://occ.oxilog.net:1443/api/v1/acl_groups/2/acls
Content-Type: application/json
Authorization: Bearer U0wglx83RzOBnkb755i8MpZtsuEjna1M7D042fihMXwJs4Tj8uhnsGuK9cIi2IY5

{
  "ip_addr": "169.48.36.56",
  "mask": "32",
  "tag": "Nexmo:SIP-08"
}

###

#Update Acl
PUT https://occ.oxilog.net:1443/api/v1/acl_groups/3/acls/1
Content-Type: application/json
Authorization: Bearer U0wglx83RzOBnkb755i8MpZtsuEjna1M7D042fihMXwJs4Tj8uhnsGuK9cIi2IY5

{
  "ip_addr": "93.201.14.73",
  "mask": "32",
  "port": 0
}

###

#Delete Acl Node
DELETE https://occ.oxilog.net:1443/api/v1/acl_groups/3/acls/1
Content-Type: application/json
Authorization: Bearer U0wglx83RzOBnkb755i8MpZtsuEjna1M7D042fihMXwJs4Tj8uhnsGuK9cIi2IY5
