                                    #########################################################################                                    
                                    ######################  Roles API ENDPOINTS TESTS   ###########################
                                    #########################################################################


#GET ALL Accounts by table name
GET http://localhost:3000/api/generateTokenForUser/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQ3OTU2MTQsImV4cCI6MTYyNTMxMTYxNH0.jVgiO2CA-vVXlT3fkGZyFUtRPytSoqm7YU03IduLB8g

{
   
}

###

#Find an item with his id
GET http://localhost:3000/api/role/find/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQ3OTU2MTQsImV4cCI6MTYyNTMxMTYxNH0.jVgiO2CA-vVXlT3fkGZyFUtRPytSoqm7YU03IduLB8g

###

#Create and Save a new item
POST http://localhost:3000/api/role/save
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQ3OTU2MTQsImV4cCI6MTYyNTMxMTYxNH0.jVgiO2CA-vVXlT3fkGZyFUtRPytSoqm7YU03IduLB8g


{
    "role_name": "Super Admin 2",
    "account_id": 0
}

###

###

#Search Items by their accountname 
GET  http://localhost:3000/api/role/search/
Content-Type: application/json

{
    "accountname" : "test loger2"
}

###

#Update an item by ID
PUT http://localhost:3000/api/role/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQ3OTU2MTQsImV4cCI6MTYyNTMxMTYxNH0.jVgiO2CA-vVXlT3fkGZyFUtRPytSoqm7YU03IduLB8g

{
   
    "role_id": 100,
    "role_name": "Super Admin updated"

}

###

#Delete an item by ID
DELETE http://localhost:3000/api/role/delete/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQ3OTU2MTQsImV4cCI6MTYyNTMxMTYxNH0.jVgiO2CA-vVXlT3fkGZyFUtRPytSoqm7YU03IduLB8g


###
