###
# GET ALL GATEWAYS

GET http://92.222.227.222:8091/api/v1/dialer/gateways
Content-Type: application/json
Authorization: Bearer LucH6JQhHjpXVhP8K6buVmGFrrYrQ9jR56Zx5Ftcq2X93fXcxRfFwrQU2Ka7J8Mr

###
# GET GATEWAY BY UUID

GET http://176.31.32.216:8091/api/v1/dialer/gateways/cc217ca9-4991-4311-bd58-aca92d008998
Content-Type: application/json
Authorization: Bearer LucH6JQhHjpXVhP8K6buVmGFrrYrQ9jR56Zx5Ftcq2X93fXcxRfFwrQU2Ka7J8Mr

###
# CREATE NEW GATEWAY

POST http://92.222.227.222:8091/api/v1/dialer/gateways
Content-Type: application/json
Authorization: Bearer LucH6JQhHjpXVhP8K6buVmGFrrYrQ9jR56Zx5Ftcq2X93fXcxRfFwrQU2Ka7J8Mr

{
  "name":"SBC",
  "username":"",
  "accountcode":"010",
  "proxy":"51.254.233.219",
  "register":false,
  "caller_id_in_from":true,
  "extension":"SBC",
  "extension_in_contact":true,
  "codec_prefs":"PCMA"
}

###
# CREATE NEW GATEWAY

POST http://176.31.32.216:8091/api/v1/dialer/gateways
Content-Type: application/json
Authorization: Bearer LucH6JQhHjpXVhP8K6buVmGFrrYrQ9jR56Zx5Ftcq2X93fXcxRfFwrQU2Ka7J8Mr

{
  "name":"voxgate",
  "username":"voxgate",
  "password":"dssfsfsfsff",
  "proxy":"sip.voxnode.com",
  "register":true,
  "expire_seconds":900,
  "retry_seconds":90,
  "caller_id_in_from":true,
  "extension":"voxgate",
  "extension_in_contact":true,
  "codec_prefs":"PCMA,PCMU"
}

###
# UPDATE GATEWAY BY UUID

PUT http://176.31.32.216:8091/api/v1/dialer/gateways/ba4c33a4-49c2-4097-b978-974a631ebb60
Content-Type: application/json
Authorization: Bearer LucH6JQhHjpXVhP8K6buVmGFrrYrQ9jR56Zx5Ftcq2X93fXcxRfFwrQU2Ka7J8Mr

{
  "name":"VOS3000",
  "username": "VOS3000",
  "extension": "VOS3000"
}

###

# DELETE GATEWAY BY UUID
DELETE http://92.222.227.222:8091/api/v1/dialer/gateways/03622c67-f888-47d7-a89f-04b2511033c3
Content-Type: application/json
Authorization: Bearer LucH6JQhHjpXVhP8K6buVmGFrrYrQ9jR56Zx5Ftcq2X93fXcxRfFwrQU2Ka7J8Mr