                                    #########################################################################                                    
                                    ######################  API ENDPOINTS utilities   ###########################
                                    #########################################################################


#GET ALL Accounts by table name
POST http://localhost:3001/api/callstatus/save
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQ3OTU2MTQsImV4cCI6MTYyNTMxMTYxNH0.jVgiO2CA-vVXlT3fkGZyFUtRPytSoqm7YU03IduLB8g

{
    "code" : "test",
     "label" : "test",
     "campaign_id" : 29
}

###
#GET ALL Accounts by table name
POST http://localhost:3001/api/testUppy
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQ3OTU2MTQsImV4cCI6MTYyNTMxMTYxNH0.jVgiO2CA-vVXlT3fkGZyFUtRPytSoqm7YU03IduLB8g

{
    "file_name" : "test efile"
}
###
DELETE  http://localhost:3001/api/callstatus/delete/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQ3OTU2MTQsImV4cCI6MTYyNTMxMTYxNH0.jVgiO2CA-vVXlT3fkGZyFUtRPytSoqm7YU03IduLB8g

{

}
###

DELETE  http://localhost:3001/api/audio/delete/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQ3OTU2MTQsImV4cCI6MTYyNTMxMTYxNH0.jVgiO2CA-vVXlT3fkGZyFUtRPytSoqm7YU03IduLB8g

{   

}
###

POST  http://localhost:3001/apicallcenter/queues
Content-Type: application/json

{
    "name": "queue-callcenter11",
    "extension": "20014",
    "accountcode": "11970",
    "strategy": "longest-idle-agent",
    "greetings": [],
    "record": false,
    "options": {
         "max_wait_time": 0,
        "time_base_score": "queue",
        "tier_rules_apply": "false",
        "tier_rule_wait_second": 300,
        "agent_no_answer_status": "on-break",
        "discard_abandoned_after": 900,
        "abandoned_resume_allowed": "true",
        "ring_progressively_delay": 10,
        "tier_rule_no_agent_no_wait": "true",
        "max_wait_time_with_no_agent": 120,
        "tier_rule_wait_multiply_level": "false",
        "skip_agents_with_external_calls": "false",
        "max_wait_time_with_no_agent_time_reached": 5
    }
}

