                                    #########################################################################                                    
                                    ######################  API ENDPOINTS utilities   ###########################
                                    #########################################################################


#GET ALL Accounts by table name
POST http://localhost:3001/api/callstatus/save
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQ3OTU2MTQsImV4cCI6MTYyNTMxMTYxNH0.jVgiO2CA-vVXlT3fkGZyFUtRPytSoqm7YU03IduLB8g

{
    "code" : "test",
     "label" : "test",
     "campaign_id" : 29
}

###
#GET ALL Accounts by table name
POST http://localhost:3001/api/testUppy
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQ3OTU2MTQsImV4cCI6MTYyNTMxMTYxNH0.jVgiO2CA-vVXlT3fkGZyFUtRPytSoqm7YU03IduLB8g

{
    "file_name" : "test efile"
}
###
DELETE  http://localhost:3001/api/callstatus/delete/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQ3OTU2MTQsImV4cCI6MTYyNTMxMTYxNH0.jVgiO2CA-vVXlT3fkGZyFUtRPytSoqm7YU03IduLB8g

{

}
###

PUT http://localhost:3001/api/pausestatus/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQ3OTU2MTQsImV4cCI6MTYyNTMxMTYxNH0.jVgiO2CA-vVXlT3fkGZyFUtRPytSoqm7YU03IduLB8g

{
    "pausestatus_id" : 1,
    "code" : "test update "
}
###

GET http://localhost:3001/apicallcenter/agents/057c5621-6722-4dfc-a4f7-5ad9cb0f4984
Content-Type: application/json


{

}

