                                    #########################################################################                                    
                                    ######################  API ENDPOINTS utilities   ###########################
                                    #########################################################################


#GET ALL Accounts by table name
POST http://localhost:3001/api/callstatus/save
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQ3OTU2MTQsImV4cCI6MTYyNTMxMTYxNH0.jVgiO2CA-vVXlT3fkGZyFUtRPytSoqm7YU03IduLB8g

{
    "code" : "test",
     "label" : "test",
     "campaign_id" : 29
}

###
#GET ALL Accounts by table name
POST http://localhost:3001/api/testUppy
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQ3OTU2MTQsImV4cCI6MTYyNTMxMTYxNH0.jVgiO2CA-vVXlT3fkGZyFUtRPytSoqm7YU03IduLB8g

{
    "file_name" : "test efile"
}
###
DELETE  http://localhost:3001/api/callstatus/delete/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjQ3OTU2MTQsImV4cCI6MTYyNTMxMTYxNH0.jVgiO2CA-vVXlT3fkGZyFUtRPytSoqm7YU03IduLB8g

{

}
###

DELETE   http://localhost:3001/apicallcenter/acl_groups/2
Content-Type: application/json

{

}
###

POST  http://localhost:3001/apicallcenter/queues/9b170edf-1a34-4f9d-90c7-64c8214032bb/tiers
Content-Type: application/json

{
    "tiers": [
        {
            "agent_uuid": "2066dab4-279f-4c6e-88a8-cf82b9ffd1ce",
            "tier_level": 1,
            "tier_position": 1
        }
    ]
}

