                                    #########################################################################                                    
                                    ######################  API ENDPOINTS TESTS   ###########################
                                    #########################################################################


#GET ALL Accounts by table name
GET http://localhost:1441/api/accounts/
Content-Type: application/json

###

#FindOne account by his primary key PK
GET http://localhost:1441/api/accounts/find/57/
Content-Type: application/json

###

#Create a new Item in the table
POST http://localhost:1441/api/accounts/create/
Content-Type: application/json


{
   "accountcode": "test 24/06",
   "accountname": "test 2"
}

###

###

#Search row in table (example accountname)
GET  http://localhost:1441/api/accounts/search/
Content-Type: application/json

{
    "accountname" : "test loger2"
}

###

#Update one Item
PUT http://localhost:1441/api/accounts/update/
Content-Type: application/json

{
    "account_id": "56",
    "accountcode": "test loger GHJKJHGFDFGHJ***********",
    "accountname": "test loger update100"
}

###
 
#Delete Item by ID
DELETE http://localhost:1441/api/accounts/delete/57
Content-Type: application/json

###
