                                    #########################################################################                                    
                                    ######################  API ENDPOINTS TESTS   ###########################
                                    #########################################################################


#GET ALL Accounts by table name
GET http://5.196.63.217:1441/api/accounts/
Content-Type: application/json

{
    "tablename" : "accounts"
}

###

#Find an item with his id
GET http://5.196.63.217:1441/api/accounts/find/184/
Content-Type: application/json

###

#Create and Save a new item
POST http://5.196.63.217:1441/api/accounts/create/
Content-Type: application/json


{
   
    "account_code": "account_code",
    "first_name": "first_name",
    "last_name": "last_name",
    "company": "company",
    "adresse": "adresse",
    "country": "country",
    "city": "city",
    "zip_code": "zip_code",
    "tel": "tel",
    "mobile": "mobile",
    "email": "email",
    "nbr_account": 10,
    "white_label": true,
    "log": "log",
    "white_label_app_name": "white_label_app_name",
    "domain": "domain"
}

###

###

#Search Items by their accountname 
GET  http://5.196.63.217:1441/api/accounts/search/
Content-Type: application/json

{
    "accountname" : "test loger2"
}

###

#Update an item by ID
PUT http://5.196.63.217:1441/api/accounts/update/
Content-Type: application/json

{
     "account_id": 183,
    "account_code": "account_code 3",
    "first_name": "first_name 2",
    "last_name": "last_name 2",
    "company": "company 2",
    "adresse": "adresse 2",
    "country": "country 2",
    "city": "city 2",
    "zip_code": "zip_code 2",
    "tel": "tel 2",
    "mobile": "mobile 2",
    "email": "email 2",
    "nbr_account": 12,
    "white_label": false,
    "log": "log 2",
    "white_label_app_name": "white_label_app_name 2",
    "domain": "domain 2"
}

###
 
#Delete an item by ID
DELETE http://5.196.63.217:1441/api/accounts/delete/183
Content-Type: application/json

###
